// 'use client'

import Header from '@/components/layout/header/Header'
import SideBar from '@/components/layout/sidebar/SideBar'
import MainProvider from '@/provider/MainProvider'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './layout.module.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

// const queryClient = new QueryClient()
export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<MainProvider>
					<div className={` container ${styles.layout}`}>
						<SideBar />

						<div>
							<Header />
							{children}
						</div>
					</div>
				</MainProvider>
			</body>
		</html>
	)
}
